# Data Stream Generator Configuration
# ===================================

Id = "plantX"
Description = "DataStreamGenerator configuration for simulated sensors on a plant"
Environment = "DEVELOPMENT" # DEVELOPMENT, PRODUCTION
Seed = -1 # >= 0 means fixed seed
Shuffle = false # shuffle order of series generation every iteration, otherwise use rank
Interval = 100 # check interval in ms
DateTimeFormat = "yyyy-MM-dd-HH-mm-ss-fff"
StartDateTime = "1000-01-01-00-00-00-000"
DecimalPrecision = 4
Duration = 500000 # 500 seconds
Type = "stream1" # stream1 = use single thread for computation of all series, stream2 = use 1 task per series defined below
BrokerHostName = "127.0.0.1" # using standard MQTT ports 1883 & 8883
BrokerHostPort = 1883



# Series Configuration
# ===================================

[[ME]] # Mathematical Expression
Id = "s1"
Export = false
Rank = 1
Delay = 100
Title = "s"
Interval = 1000
C = 15.0
Mean = 0.0
StdDev = 0.05
Arguments = ["i"] # i = continous iterator variable (inclusive delay)
Expression = "4 * ( sin(i/5.0) + sin(2*i/5.0)/2 + sin(5*i/5.0)/7 )"

[[ARMA]] # Auto Regressive Moving Average series
Id = "s2"
Rank = 2
Export = true
Delay = 100
Interval = 1000
Topic = "raw/plantx/s2"
Title = "s2"
P = [0.1, 0.05, 0.01]
Q = [0.02, 0.01]
C = 5.0
Mean = 0.0
StdDev = 0.2
    [[ARMA.Drivers]]
    Id = "s1"
    P = [0.5, 0.35]

[[ARMA]] # Auto Regressive Moving Average series
Id = "s3"
Rank = 3
Export = true
Delay = 100
Interval = 1000
Topic = "raw/plantx/s3"
Title = "s3"
P = [0.1, 0.05, 0.01]
Q = [0.02, 0.01]
C = 5.0
Mean = 0.0
StdDev = 0.2
    [[ARMA.Drivers]]
    Id = "s1"
    P = [0.5, 0.25, -0.15]