# Data Stream Generator Configuration
# ===================================

Id = "plantX"
Description = "DataStreamGenerator configuration for simulated sensors on a plant"
Environment = "DEVELOPMENT" # DEVELOPMENT, PRODUCTION
Seed = -1 # >= 0 means fixed seed
Shuffle = false # shuffle order of series generation every iteration, otherwise use rank
Interval = 100 # check interval in ms
DateTimeFormat = "yyyy-MM-dd-HH-mm-ss-fff"
StartDateTime = "1000-01-01-00-00-00-000"
DecimalPrecision = 4
Duration = 500000 # 500 seconds
Type = "generate1"
OutputFilePath = "..\\..\\..\\generateddataset.csv" # modify path
Separator = ";"
ExportIdAsHeader = true
ExportDateTime = true
ExportEventCount = false
ExportLags = [1,2,3,4,5,6,7,8,9,10] # number of lags to export for each variable to be exported below



# Series
# =====================================

[[ARMA]] # Auto Regressive Moving Average series
Id = "s1"
Rank = 1
Export = false
Delay = 100
Interval = 1000
Title = "s1"
P = [0.1, 0.05, 0.01]
Q = [0.02, 0.01]
C = 5.0
Mean = 0.0
StdDev = 0.2

[[XF]] # eXternal File based series
Id = "s2"
Rank = 2
Export = false
Delay = 0
Interval = 1000
Title = "s2"
SourcePath = "C:\\<...>\\datasettoreplay.csv" # modify path
SourceIndex = ",0" # use column 0, "0," = use row 0

[[MEMC]] # Mathematical Expression with Multiple Conditions (to simulate different plant-states at some point in time)
Id = "s3"
Rank = 3
Export = true
Delay = 1000
Interval = 1000
Title = "s3"
C = 10.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", # event counter including delay
            "c", # event counter after delay
            "s1", # last value of series with id "s1"
            "s1_1", # value of series "s1" at c-1
            "s2"] # last value of series "s2"
Conditions = ["c>=100 && c<=150", "c>=350 && c<=375"]
Expressions =   [
                "(s1 - s1_1) * s2 + sin(i/14)*5", # if condition[0] == true
                "(s1 - s1_1) * s2 + sin(i/16)*2", # if condition[1] == true
                "(s1 - s1_1) * s2 + sin(i/15)*3" # default expression
                ]