# Data Stream Generator Configuration
# ===================================

Id = "plantB"
Description = "DataStreamGenerator configuration for simulated sensors on plant B, which is (somehow) dependent on plant A"
Environment = "DEVELOPMENT" # DEVELOPMENT, PRODUCTION
Seed = -1 # >= 0 means fixed seed
Shuffle = false # shuffle order of series generation every iteration, otherwise use rank
Interval = 100 # check interval in ms
DateTimeFormat = "yyyy-MM-dd-HH-mm-ss-fff"
StartDateTime = "1000-01-01-00-00-00-000"
DecimalPrecision = 4
Duration = 500000 # 500 seconds
Type = "stream1"
BrokerHostName = "127.0.0.1"
BrokerHostPort = 1883



# Series Configuration
# ===================================

[[XG]] # eXternally Generated series
Id = "s2"
Rank = 1
Export = false
Delay = 100
Interval = 1000
Topic = "raw/plantb/s2"
Title = "s2"
SourceBroker = "127.0.0.1"
SourceTopic = "raw/planta/s1"

[[ARMA]] # Auto Regressive Moving Average series
Id = "s3"
Rank = 1
Export = true
Delay = 100
Interval = 1000
Topic = "raw/plantb/s3"
Title = "s3"
P = [0.1, 0.05, 0.01]
Q = [0.02, 0.01]
C = 5.0
Mean = 0.0
StdDev = 0.2
    [[ARMA.Drivers]]
    Id = "s2"
    P = [0.5, 0.35, 0.2]