# Data Stream Generator Configuration
# ===================================

Id = "plantX"
Description = "DataStreamGenerator configuration for simulated sensors on a plant"
Environment = "DEVELOPMENT" # DEVELOPMENT ("group"-field in MQTT message -- when streaming -- is random), PRODUCTION ("group"-field equals Id, i.e. here "plantX")
Seed = -1 # >= 0 means fixed seed
Shuffle = false # shuffle order of series generation every iteration, otherwise use rank
Interval = 100 # check interval in ms
DateTimeFormat = "yyyy-MM-dd-HH-mm-ss-fff"
StartDateTime = "1000-01-01-00-00-00-000"
DecimalPrecision = 4 # precision of produced double values
Duration = 500000 # 500 seconds
Type = "generate1" # generate1 = datetime based computation (interval & delay in milliseconds), generate2 = event count based computation
OutputFilePath = "..\\..\\..\\generateddataset.csv" # modify path
Separator = ";" # csv separator
ExportIdAsHeader = true
ExportDateTime = true
ExportEventCount = false



# Series
# ===================================

[[ME]] # Mathematical Expression
Id = "s1"
Export = true
Rank = 1
Delay = 100 # length of "burn-in" phase
Title = "s"
Interval = 1000
C = 15.0 # additive constant term
Mean = 0.0 # additive noise term
StdDev = 0.05 # cf. noise term
Arguments = ["i"] # i = continous iterator variable (inclusive delay)
Expression = "4 * ( sin(i/5.0) + sin(2*i/5.0)/2 + sin(5*i/5.0)/7 )" # function body of s1(i)

[[AR]] # Auto Regressive series
Id = "s2"
Rank = 2
Export = true
Delay = 1000
Interval = 1000
Title = "s2"
P = [0.4, 0.08, 0.002] # auto regressive part
C = 10.0
Mean = 0.0 # noise term, for AR models also called "shock" or "impulse"
StdDev = 0.1 # cf. noise term


[[ARMA]] # Auto Regressive Moving Average series
Id = "s3"
Rank = 3
Export = true
Delay = 1000
Interval = 1000
Title = "s3"
P = [0.1, 0.05, 0.01] # auto regressive part
Q = [0.02, 0.01] # moving average part
C = 5.0
Mean = 0.0
StdDev = 0.2
OutlierRatio1s = 0.05 # 1-2 sigma outlier
OutlierRatio2s = 0.005 # 2+ sigma outlier
    [[ARMA.Drivers]]
    Id = "s1"
    P = [0.75, 0.35, 0.10]
    [[ARMA.Drivers]]
    Id = "s2"
    P = [0.15, 0.05, 0.02]

[[ARIMA]] # Auto Regressive Integrated Moving Average series
Id = "s4"
Rank = 4
Export = true
Delay = 1000
Interval = 1000
Title = "s4"
P = [0.1, 0.05, 0.01]
Q = [0.02, 0.01]
I = 2 # number of integration steps
C = 5.0
Mean = 0.0
StdDev = 0.2

