# Data Stream Generator Configuration
# ===================================

Id = "plantX"
Description = "DataStreamGenerator configuration for simulated sensors on a plant"
Environment = "DEVELOPMENT" # DEVELOPMENT, PRODUCTION
Seed = -1 # >= 0 means fixed seed
Shuffle = false # shuffle order of series generation every iteration, otherwise use rank
Interval = 100 # check interval in ms
DateTimeFormat = "yyyy-MM-dd-HH-mm-ss-fff"
StartDateTime = "1000-01-01-00-00-00-000"
DecimalPrecision = 4
Duration = 1000000 # 1000 seconds
Type = "generate1"
OutputFilePath = "..\\..\\..\\generateddataset_conceptdrifts1.csv" # modify path
Separator = ";"
ExportIdAsHeader = true
ExportDateTime = false
ExportEventCount = true
# ExportLags = [1,2,3,4,5,6,7,8,9,10] # number of lags to export for each variable to be exported below



# Series
# =====================================

# s1 = {1,2,3} # which sensor string is currently "at work", i.e. processing material. The others are in idle mode
# =====================================
[[IS]]
Id = "s1"
Rank = 1
Export = true
Delay = 1000
Interval = 1000
Title = "s1"
Min = 1
Max = 3
MinLength = 2
MaxLength = 10

# sd = {0,1,2,3} # which sensor is drifting?
# =====================================
[[IS]]
Id = "sd"
Rank = 2
Export = true
Delay = 1000
Interval = 1000
Title = "sd"
Min = 2
Max = 10
MinLength = 100
MaxLength = 101

# dt = [10,20] # drift type
# =====================================
[[IS]]
Id = "dt"
Rank = 3
Export = true
Delay = 1000
Interval = 1000
Title = "sd"
Min = 10
Max = 20
MinLength = 100
MaxLength = 101

# sensor drifts
# =====================================
[[MEMC]]
Id = "s2d"
Rank = 4
Export = true
Delay = 1000
Interval = 1000
Title = "s2d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==2"]
Expressions = ["(sin(i/dt)*7 + 10)", "0.0"]

[[MEMC]]
Id = "s3d"
Rank = 5
Export = true
Delay = 1000
Interval = 1000
Title = "s3d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==3"]
Expressions = ["(cos(i/dt)*5 + 10)", "0.0"]

[[MEMC]]
Id = "s4d"
Rank = 6
Export = true
Delay = 1000
Interval = 1000
Title = "s4d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==4"]
Expressions = ["(sin(i/dt)*3 + 10)", "0.0"]

[[MEMC]]
Id = "s5d"
Rank = 7
Export = true
Delay = 1000
Interval = 1000
Title = "s5d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==5"]
Expressions = ["(sin(i/dt)*6.5 + 10)", "0.0"]

[[MEMC]]
Id = "s6d"
Rank = 8
Export = true
Delay = 1000
Interval = 1000
Title = "s6d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==6"]
Expressions = ["(cos(i/dt)*5.5 + 10)", "0.0"]

[[MEMC]]
Id = "s7d"
Rank = 9
Export = true
Delay = 1000
Interval = 1000
Title = "s7d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==7"]
Expressions = ["(sin(i/dt)*2.7 + 10)", "0.0"]

[[MEMC]]
Id = "s8d"
Rank = 10
Export = true
Delay = 1000
Interval = 1000
Title = "s8d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==8"]
Expressions = ["(sin(i/dt)*7.25 + 10)", "0.0"]

[[MEMC]]
Id = "s9d"
Rank = 11
Export = true
Delay = 1000
Interval = 1000
Title = "s9d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==9"]
Expressions = ["(cos(i/dt)*4.2 + 10)", "0.0"]

[[MEMC]]
Id = "s10d"
Rank = 12
Export = true
Delay = 1000
Interval = 1000
Title = "s10d"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "sd", "dt"]
Conditions = ["sd==10"]
Expressions = ["(sin(i/dt)*3.2 + 10)", "0.0"]



# s1 = 1 (s2, s3, s4 => s5)
# =====================================

[[MEMC]]
Id = "s2"
Rank = 22
Export = true
Delay = 1000
Interval = 1000
Title = "s2"
C = 100.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", # event counter including delay
            "c", # event counter after delay
            "s1", "sd", "s2d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s2d + sin(i/5.0) + sin(2*i/5.0)/2 + sin(5*i/5.0)/7",
                "s2d/2 + sin(i/5.0) + sin(2*i/5.0)/2",
                "s2d/2 + sin(i/5.0) + sin(2*i/5.0)/2"] 

[[MEMC]]
Id = "s3"
Rank = 23
Export = true
Delay = 1000
Interval = 1000
Title = "s3"
C = 12.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "sd", "s3d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s3d + cos(i/7.0) + cos(3*i/7.0)/2 + sin(5*i/5.0)/7",
                "s3d/2 + cos(i/7.0) + cos(3*i/7.0)/2",
                "s3d/2 + cos(i/7.0) + cos(3*i/7.0)/2"]

[[MEMC]]
Id = "s4"
Rank = 24
Export = true
Delay = 1000
Interval = 1000
Title = "s4"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "sd", "s4d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s4d/10 + cos(i)/4.2 + 1",
                "s4d/20 + cos(i)/4 + 1",
                "s4d/20 + cos(i)/4 + 1"]

[[ME]] 
Id = "s234"
Export = true
Rank = 101
Delay = 1000
Title = "s234"
Interval = 1000
C = 0.0
Mean = 0.0 # additive noise term
StdDev = 0.00 # cf. noise term
Arguments = ["i", "s2", "s3", "s4"] 
Expression = "s2 * s3 * cos(s4)" # active power + error term


# s1 = 2 (s5, s6, s7 => s567)
# =====================================

[[MEMC]]
Id = "s5"
Rank = 25
Export = true
Delay = 1000
Interval = 1000
Title = "s5"
C = 100.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "s5d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s5d/2 + sin(i/4.0) + sin(2*i/3.0)/2",
                "s5d + sin(i/4.0) + sin(2*i/3.0)/2 + sin(5*i/3.0)/6",
                "s5d/2 + sin(i/4.0) + sin(2*i/3.0)/2"] 

[[MEMC]]
Id = "s6"
Rank = 26
Export = true
Delay = 1000
Interval = 1000
Title = "s6"
C = 16.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "s6d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s6d/2 + cos(i/7.0) + cos(3*i/7.0)/2",
                "s6d + cos(i/7.0) + cos(3*i/7.0)/2 + sin(5*i/5.0)/7",
                "s6d/2 + cos(i/7.0) + cos(3*i/7.0)/2"]

[[MEMC]]
Id = "s7"
Rank = 27
Export = true
Delay = 1000
Interval = 1000
Title = "s7"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "s7d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s7d/20 + cos(i)/4 + 1",
                "s7d/10 + cos(i)/4.2 + 1",
                "s7d/20 + cos(i)/4 + 1"]

[[ME]] 
Id = "s567"
Export = true
Rank = 102
Delay = 1000
Title = "s567"
Interval = 1000
C = 0.0
Mean = 0.0 # additive noise term
StdDev = 0.00 # cf. noise term
Arguments = ["i", "s5", "s6", "s7"] 
Expression = "s5 * s6 * cos(s7)" # active power + error term

# s1 = 3 (s8, s9, s10 => s8910)
# =====================================

[[MEMC]]
Id = "s8"
Rank = 28
Export = true
Delay = 1000
Interval = 1000
Title = "s8"
C = 80.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "s8d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s8d/2 + sin(i/4.0) + sin(2*i/3.0)/2",
                "s8d/2 + sin(i/4.0) + sin(2*i/3.0)/2",
                "s8d + sin(i/4.0) + sin(2*i/3.0)/2 + sin(4*i/3.0)/6"] 

[[MEMC]]
Id = "s9"
Rank = 29
Export = true
Delay = 1000
Interval = 1000
Title = "s9"
C = 12.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "s9d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s9d/2 + cos(i/7.0) + cos(3*i/7.0)/2",
                "s9d/2 + cos(i/7.0) + cos(3*i/7.0)/2",
                "s9d + cos(i/7.0) + cos(3*i/7.0)/2 + sin(5*i/5.0)/7"]

[[MEMC]]
Id = "s10"
Rank = 30
Export = true
Delay = 1000
Interval = 1000
Title = "s10"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "s10d"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "s10d/20 + cos(i)/4 + 1",
                "s10d/20 + cos(i)/4 + 1",
                "s10d/10 + cos(i)/4.2 + 1"]

[[ME]] 
Id = "s8910"
Export = true
Rank = 103
Delay = 1000
Title = "s8910"
Interval = 1000
C = 0.0
Mean = 0.0 # additive noise term
StdDev = 0.00 # cf. noise term
Arguments = ["i", "s8", "s9", "s10"] 
Expression = "s8 * s9 * cos(s10)" # active power + error term


# (s123, s456, s8910) => s99
# =====================================

[[MEMC]]
Id = "s99"
Rank = 999
Export = true
Delay = 1000
Interval = 1000
Title = "s99"
C = 0.0
Mean = 0.0
StdDev = 0.0
Arguments = ["i", "c", "s1", "s234", "s567", "s8910"]
Conditions = ["s1==1", "s1==2"]
Expressions =   [
                "sin(i/5)/4 + cos(3*i/7)/5 + s234",
                "sin(i/5)/4 + cos(3*i/7)/5 + s567",
                "sin(i/5)/4 + cos(3*i/7)/5 + s8910"]

